# Generated by Django 4.2 on 2024-02-04 13:42

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('mines_count', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('field', models.JSONField(default=list)),
            ],
        ),
    ]
